import { FC } from "react";
import Styles from "./Specification.module.scss";

const SpecificationTable2: FC = () => {
  return (
    <div className={Styles.specification_table2_box}>
      <table className={Styles.specification_table2_box_header}>
        <tbody>
          <tr>
            <th className={Styles.specification_table2_box_header_title}>
              Измерение шума (октавы)
            </th>
            <th className={Styles.specification_table2_box_header_title}>М</th>
            <th className={Styles.specification_table2_box_header_title}>
              63Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              125Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              250Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              500Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              1kHz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              2kHz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              4kHz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              8kHz
            </th>
          </tr>
        </tbody>
      </table>
      <div className={Styles.specification_table2_box_table_container}>
        <div
          className={
            Styles.specification_table2_box_table_container_right_block
          }
        >
          <div
            className={
              Styles.specification_table2_box_table_container_right_block_item
            }
          >
            УЗМ на выходе
          </div>
          <div
            className={
              Styles.specification_table2_box_table_container_right_block_item
            }
          >
            LWA6
          </div>
          <div
            className={
              Styles.specification_table2_box_table_container_right_block_item
            }
          >
            dW(A)
          </div>
        </div>
        <table
          className={
            Styles.specification_table2_box_table_container_right_block_line
          }
        >
          <tbody>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                1
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                85
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                63
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                71
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                78
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                80
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                79
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                77
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                68
              </th>
            </tr>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                2
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                81
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                56
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                68
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                73
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                74
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                72
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                65
              </th>
            </tr>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                3
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                81
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                59
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                72
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                74
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                73
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                71
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                65
              </th>
            </tr>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                4
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                81
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                61
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                69
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                73
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                76
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                72
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                68
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                73
              </th>
            </tr>
            <tr className="bottom__box-size">
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                5
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                84
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                58
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                72
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                77
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                76
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                74
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                70
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                79
              </th>
            </tr>
          </tbody>
        </table>
      </div>
      <table className={Styles.specification_table2_box_header}>
        <tbody>
          <tr>
            <th className={Styles.specification_table2_box_header_title}>
              Измерение шума (октавы)
            </th>
            <th className={Styles.specification_table2_box_header_title}>М</th>
            <th className={Styles.specification_table2_box_header_title}>
              63Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              125Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              250Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              500Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              1kHz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              2kHz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              4kHz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              8kHz
            </th>
          </tr>
        </tbody>
      </table>
      <div className={Styles.specification_table2_box_table_container}>
        <div
          className={
            Styles.specification_table2_box_table_container_right_block
          }
        >
          <div
            className={
              Styles.specification_table2_box_table_container_right_block_item
            }
          >
            УЗМ на входе
          </div>
          <div
            className={
              Styles.specification_table2_box_table_container_right_block_item
            }
          >
            LWA5
          </div>
          <div
            className={
              Styles.specification_table2_box_table_container_right_block_item
            }
          >
            dW(A)
          </div>
        </div>
        <table
          className={
            Styles.specification_table2_box_table_container_right_block_line
          }
        >
          <tbody>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                1
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                85
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                63
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                71
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                78
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                80
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                79
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                77
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                68
              </th>
            </tr>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                2
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                81
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                56
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                68
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                73
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                74
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                72
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                65
              </th>
            </tr>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                3
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                81
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                59
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                72
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                74
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                73
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                71
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                65
              </th>
            </tr>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                4
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                81
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                61
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                69
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                73
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                76
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                72
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                68
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                73
              </th>
            </tr>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                5
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                84
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                58
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                72
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                75
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                77
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                76
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                74
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                70
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                79
              </th>
            </tr>
          </tbody>
        </table>
      </div>
      <table className={Styles.specification_table2_box_header}>
        <tbody>
          <tr>
            <th className={Styles.specification_table2_box_header_title}>
              Измерение шума (октавы)
            </th>
            <th className={Styles.specification_table2_box_header_title}>М</th>
            <th className={Styles.specification_table2_box_header_title}>
              63Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              125Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              250Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              500Hz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              1kHz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              2kHz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              4kHz
            </th>
            <th className={Styles.specification_table2_box_header_title}>
              8kHz
            </th>
          </tr>
        </tbody>
      </table>
      <div className={Styles.specification_table2_box_table_container}>
        <div
          className={
            Styles.specification_table2_box_table_container_right_block
          }
        >
          <div
            className={
              Styles.specification_table2_box_table_container_right_block_item
            }
          >
            УЗМ на входе
          </div>
          <div
            className={
              Styles.specification_table2_box_table_container_right_block_item
            }
          >
            LWA5
          </div>
          <div
            className={
              Styles.specification_table2_box_table_container_right_block_item
            }
          >
            dW(A)
          </div>
        </div>
        <table
          className={
            Styles.specification_table2_box_table_container_right_block_line
          }
        >
          <tbody>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                1
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
            </tr>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                2
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
            </tr>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                3
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
            </tr>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                4
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
            </tr>
            <tr>
              <th
                className={Styles.specification_table2_box_table_container_gray}
              >
                5
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
              <th
                className={
                  Styles.specification_table2_box_table_container_green
                }
              >
                -
              </th>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};

export { SpecificationTable2 };
