image: node:latest

services:
  - postgres:latest

cache:
  paths:
    - node_modules/
npm_install:
  script:
    - npm install
    - npm install git

project_build:
  script:
    - npm run build

test_lint:
  script:
    - npm run lint

unit_test:
  script:
    - npm run test

deploy:
  script:
    - git init 
    - git remote -v
    - git branch
    - git config pull.rebase true
    - git pull origin master
    - git remote add pb ssh://root@213.139.210.18:/root/veza/front/.git
    - git remote -v
    - git remote show pb

