image: node:latest
stages:
  - preparation
  - build
  - test
  - deploy_staging


install_dependencies:
    stage: preparation
    script:
      - npm install
      - npm install git
    tags:
      - stagin
    artifacts:
      paths:
        - /     

build:
  stage: build
  script:
    - npm run build
  tags:
    - stagin  
  artifacts:
    paths:
      - /     

testing:
  dependencies:
    - build
  stage: test
  script: npm run test

deploy_staging:
  stage: deploy_staging
  only:
    - master
  script:
    - echo "test" 
