image: node:latest

stages:
  - install
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
    stage: install
    script:
      - npm install
      - npm install git
    artifacts:
      paths:
        - node_modules/    

build:
    stage: build
    script:
      - npm run buld

testing:
    stage: test
    script: npm run test        