image: node:latest
stages:
  - prepare_test
  - build
  - test
  - clear_images
  - deploy_staging

prepare:
  stage: prepare_test
  script:
    - npm install
    - npm run lint
  tags:
    - stagin  
    
build:
  stage: build
  script:
    - npm install
    - npm run build
  tags:
    - stagin  

testing:
  dependencies:
    - build
  stage: test
  script: 
    - npm install
    - npm run test
  tags:
    - stagin  
clear_images:
  stage: clear_images
  script:
    - docker image prune -f

deploy_staging:
  stage: deploy_staging
  only:
    - master
  script:
    - echo "test" 
