image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: https://docs.gitlab.com/ee/ci/services/index.html
services:
  - postgres:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/
npm_install:
  script:
    - npm install

project_build:
  script:
    -npm run build

test_lint:
  script:
    - npm run lint

unit_test:
  script:
    - npm run test

