image: node:latest
stages:
  - preparation
  - build
  - test
  - deploy staging


install_dependencies:
    stage: preparation
    script:
      - npm install
      - npm install git
    artifacts:
      paths:
        - /    
    only:
      - master

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - /     
  only:
    - master
    

testing:
  dependencies:
    - build
  stage: test
  script: npm run test
  only:
    - master
