image: node:latest
stages:
  - build
  - test
  - deploy_staging


build:
  stage: build
  script:
    - npm install
    - npm run build
  tags:
    - stagin  

testing:
  dependencies:
    - build
  stage: test
  script: npm run test

deploy_staging:
  stage: deploy_staging
  only:
    - master
  script:
    - echo "test" 
