image: node:latest
stages:
  - preparation
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
    stage: preparation
    script:
      - npm install
      - npm install git
    artifacts:
      paths:
        - node_modules/    
    only:
      - master

build:
  stage: build
  script:
    - npm run buld
  only:
    - master
    

testing:
  dependencies:
    - build
  stage: test
  script: npm run test
  only:
    - master
