image: node:latest
stages:
  - install_prepare
  - build
  - test
  - deploy_staging

prepare:
  stage: install_prepare
  script:
    - npm install
  artifacts:
    paths:
      - /builds/web/
    exclude:
      - /builds/web/front/.git
      - /builds/web/front/.next
      - /builds/web/front/front.tmp
  tags:
    - stagin  
    
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - /builds/web/
  tags:
    - stagin  

testing:
  dependencies:
    - build
  stage: test
  script: npm run test
  tags:
    - stagin  

deploy_staging:
  stage: deploy_staging
  only:
    - master
  script:
    - echo "test" 
