image: node:latest
stages:
  - prepare_test
  - build
  - test
  - deploy_staging

prepare:
  stage: prepare_test
  script:
    - npm install
    - npm run lint
  tags:
    - stagin  
    
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - /builds/web/
  tags:
    - stagin  

testing:
  dependencies:
    - build
  stage: test
  script: npm run test
  tags:
    - stagin  

deploy_staging:
  stage: deploy_staging
  only:
    - master
  script:
    - echo "test" 
