version: "3.9"
services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    command: start
    networks:
      - veza
  backend:
    build:
      context: ./back
    ports:
      - "5000:80"
    command: dotnet run
    networks:
      - veza
  nginx:
    build:  
      context: ./front/deploy/.nginx/
    ports:
      - "80:80"
    links:
      - nextjs
    restart: always
    networks:
      - veza
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "veza"
      POSTGRES_USER: "veza_user"
      POSTGRES_PASSWORD: "veza_user"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - veza
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.15
    environment:
      PGADMIN_DEFAULT_EMAIL: "rybolov@veza.ru"
      PGADMIN_DEFAULT_PASSWORD: "veza_user"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - veza

networks:
  veza:
    driver: bridge
