export { WhoWeContainer as WhoWe } from "./tab_who_we/WhoWeContainer";
export { ReferencesContainer as References } from "./tab_references/ReferencesContainer";
export { JobContainer as Job } from "./tab_job/JobContainer";
export { WhoWeAboutContainer as WhoWeAbout } from "./tab_who_we/about/WhoWeAboutContainer";
export { AchievementsContainer as Achievements } from "./tab_who_we/achievements/AchievementsContainer";
export { AchievementsItem } from "./tab_who_we/achievements/AchievementsItem";
export { MapContainer as WhoWeMap } from "../../components/map/MapContainer";
export { CommercialContainer as Commercial } from "./tab_references/CommercialContainer";
export { IndustrialContainer as Industrial } from "./tab_references/IndustrialContainer";
export { SocialContainer as Social } from "./tab_references/SocialContainer";
export { MapItem } from "../../components/map/MapItem";
export { referenceData } from "./tab_references/mockData";
export type { IReferencesImages } from "./tab_references/References";
export type { IWhoWeAboutData } from "./tab_who_we/about/WhoWeAbout";
