import { ICatalog, ICertificates, IQuestionnaires } from "./tab_bim/Bim";

const catalogData: ICatalog[] = [
  {
    id: 1,
    title: "Центральные кондиционеры ВЕРОСА",
    image: "/images/vran-1.jpg",
    download_url: "/download/res.pdf",
    alias: "vran1",
  },
  {
    id: 2,
    title: "Шкаф систем автоматического управления ШСАУ ВЕРСА 100",
    image: "/images/vran-1.jpg",
    download_url: "/download/res.pdf",
    alias: "vran2",
  },
  {
    id: 3,
    title: "Кондиционеры компактные панельные Airmate®",
    image: "/images/vran-1.jpg",
    download_url: "/download/res.pdf",
    alias: "vran3",
  },
  {
    id: 4,
    title: "Прецизионные кондиционеры АКП",
    image: "/images/vran-1.jpg",
    download_url: "/download/res.pdf",
    alias: "vran4",
  },
  {
    id: 5,
    title: "Приточно-вытяжные установки для бассейнов АКВАРИС®",
    image: "/images/vran-1.jpg",
    download_url: "/download/res.pdf",
    alias: "vran5",
  },
  {
    id: 6,
    title: "Приточно-вытяжные установки для бассейнов АКВАРИС®",
    image: "/images/vran-1.jpg",
    download_url: "/download/res.pdf",
    alias: "vran5",
  },
  {
    id: 7,
    title: "Приточно-вытяжные установки для бассейнов АКВАРИС®",
    image: "/images/vran-1.jpg",
    download_url: "/download/res.pdf",
    alias: "vran5",
  },
  {
    id: 8,
    title: "Приточно-вытяжные установки для бассейнов АКВАРИС®",
    image: "/images/vran-1.jpg",
    download_url: "/download/res.pdf",
    alias: "vran5",
  },
  {
    id: 9,
    title: "Приточно-вытяжные установки для бассейнов АКВАРИС®",
    image: "/images/vran-1.jpg",
    download_url: "/download/res.pdf",
    alias: "vran5",
  },
  {
    id: 10,
    title: "Приточно-вытяжные установки для бассейнов АКВАРИС®",
    image: "/images/vran-1.jpg",
    download_url: "/download/res.pdf",
    alias: "vran5",
  },
  {
    id: 11,
    title: "Приточно-вытяжные установки для бассейнов АКВАРИС®",
    image: "/images/vran-1.jpg",
    download_url: "/download/res.pdf",
    alias: "vran5",
  },
];

const sertificatesData: ICertificates[] = [
  {
    id: 1,
    image: "sertificat_1.jpg",
    download_url: "",
    category: "Название категории",
    parent: 0,
    alias: "sert1",
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 2,
    image: "sertificat_2.jpg",
    download_url: "",
    category: "Название категории",
    parent: 0,
    alias: "sert2",
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 3,
    image: "sertificat_3.jpg",
    download_url: "",
    category: "Название категории",
    parent: 0,
    alias: "sert3",
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 4,
    image: "sertificat_4.jpg",
    download_url: "",
    category: "Название категории",
    parent: 0,
    alias: "sert4",
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 5,
    image: "sertificat_3.jpg",
    download_url: "",
    category: "Название категории",
    parent: 0,
    alias: "sert3",
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 6,
    image: "sertificat_4.jpg",
    download_url: "",
    category: "Название категории",
    parent: 0,
    alias: "sert4",
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 7,
    image: "sertificat_3.jpg",
    download_url: "",
    category: "Название категории",
    parent: 0,
    alias: "sert3",
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 8,
    image: "sertificat_4.jpg",
    download_url: "",
    category: "Название категории",
    parent: 0,
    alias: "sert4",
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 9,
    image: "sertificat_5.jpg",
    download_url: "",
    category: "Название категории",
    parent: 1,
    alias: "sert5",
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 10,
    image: "sertificat_6.jpg",
    download_url: "",
    category: "Название категории",
    parent: 1,
    alias: "sert6",
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 11,
    image: "sertificat_1.jpg",
    download_url: "",
    category: "Название категории",
    parent: 1,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 12,
    image: "sertificat_2.jpg",
    download_url: "",
    category: "Название категории",
    parent: 1,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 13,
    image: "sertificat_1.jpg",
    download_url: "",
    category: "Название категории",
    parent: 1,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 14,
    image: "sertificat_3.jpg",
    download_url: "",
    category: "Название категории",
    parent: 1,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 15,
    image: "sertificat_5.jpg",
    download_url: "",
    category: "Название категории",
    parent: 2,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 16,
    image: "sertificat_2.jpg",
    download_url: "",
    category: "Название категории",
    parent: 2,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 17,
    image: "sertificat_4.jpg",
    download_url: "",
    category: "Название категории",
    parent: 2,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 18,
    image: "sertificat_1.jpg",
    download_url: "",
    category: "Название категории",
    parent: 2,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 19,
    image: "sertificat_3.jpg",
    download_url: "",
    category: "Название категории",
    parent: 2,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 20,
    image: "sertificat_4.jpg",
    download_url: "",
    category: "Название категории",
    parent: 2,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 21,
    image: "sertificat_1.jpg",
    download_url: "",
    category: "Название категории",
    parent: 2,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 22,
    image: "sertificat_3.jpg",
    download_url: "",
    category: "Название категории",
    parent: 2,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 23,
    image: "sertificat_1.jpg",
    download_url: "",
    category: "Название категории",
    parent: 3,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 24,
    image: "sertificat_2.jpg",
    download_url: "",
    category: "Название категории",
    parent: 3,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 25,
    image: "sertificat_5.jpg",
    download_url: "",
    category: "Название категории",
    parent: 3,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 26,
    image: "sertificat_3.jpg",
    download_url: "",
    category: "Название категории",
    parent: 3,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 27,
    image: "sertificat_2.jpg",
    download_url: "",
    category: "Название категории",
    parent: 3,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 28,
    image: "sertificat_5.jpg",
    download_url: "",
    category: "Название категории",
    parent: 3,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 29,
    image: "sertificat_3.jpg",
    download_url: "",
    category: "Название категории",
    parent: 3,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 30,
    image: "sertificat_2.jpg",
    download_url: "",
    category: "Название категории",
    parent: 4,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 31,
    image: "sertificat_1.jpg",
    download_url: "",
    category: "Название категории",
    parent: 4,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 32,
    image: "sertificat_4.jpg",
    download_url: "",
    category: "Название категории",
    parent: 4,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 33,
    image: "sertificat_3.jpg",
    download_url: "",
    category: "Название категории",
    parent: 4,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 34,
    image: "sertificat_4.jpg",
    download_url: "",
    category: "Название категории",
    parent: 4,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 35,
    image: "sertificat_3.jpg",
    download_url: "",
    category: "Название категории",
    parent: 4,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
  {
    id: 36,
    image: "sertificat_2.jpg",
    download_url: "",
    category: "Название категории",
    parent: 4,
    title: "Название сертификата",
    desc: " Vero ducimus id vitae ad dolor aliquam, tenetur cumque ab atque cum consequatur eaque sed soluta nihil inventore eveniet!",
  },
];

const questionnairesData: IQuestionnaires[] = [
  {
    id: 1,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "КЛАПАН ПРОТИВОПОЖАРНЫЙ УНИВЕРСАЛЬНЫЙ КПУ-1Н",
    image: "1.WEBP",
    alias: "form_1",
    parent: 0,
  },
  {
    id: 2,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "ЛЮК ДЫМОУДАЛЕНИЯ",
    image: "2.WEBP",
    alias: "form_2",
    parent: 0,
  },
  {
    id: 3,
    title: "Опросный лист для проектирования децентрализованных систем: ",
    subtitle: "",
    image: "3.WEBP",
    alias: "form_3",
    parent: 0,
  },
  {
    id: 4,
    title: "Опросный лист для проектирования децентрализованных систем: ",
    subtitle: "",
    image: "4.WEBP",
    alias: "form_4",
    parent: 0,
  },
  {
    id: 5,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "УСТАНОВКИ ВЕНТИЛЯЦИОННЫЕ ПРИТОЧНО-ВЫТЯЖНЫЕ «АКВАРИС»",
    image: "5.WEBP",
    alias: "form_5",
    parent: 0,
  },
  {
    id: 6,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "ЗАВЕСЫ AEROBLAST ВКЗ",
    image: "6.WEBP",
    alias: "form_6",
    parent: 0,
  },
  {
    id: 7,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "АГРЕГАТЫ ВОЗДУШНОГО ОТОПЛЕНИЯ АВО",
    image: "7.WEBP",
    alias: "form_7",
    parent: 0,
  },
  {
    id: 8,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "СИСТЕМЫ АВТОМАТИКИ ПРИТОЧНОЙ УСТАНОВКИ",
    image: "8.WEBP",
    alias: "form_8",
    parent: 0,
  },
  {
    id: 9,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "ЧИЛЛЕР (ВОДООХЛАЖДАЮЩАЯ ХОЛОДИЛЬНАЯ МАШИНА)",
    image: "9.WEBP",
    alias: "form_9",
    parent: 0,
  },
  {
    id: 10,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "ЦЕНТРАЛЬНЫЙ КОНДИЦИОНЕР",
    image: "10.WEBP",
    alias: "form_10",
    parent: 0,
  },
  {
    id: 11,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "КОНДИЦИОНЕР AIRMATE",
    image: "11.WEBP",
    alias: "form_11",
    parent: 0,
  },
  {
    id: 12,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "КЛАПАН ПРОТИВОПОЖАРНЫЙ ДЫМОУДАЛЕНИЯ КЭД",
    image: "12.WEBP",
    alias: "form_12",
    parent: 0,
  },
  {
    id: 13,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "КЛАПАН ПРОТИВОПОЖАРНЫЙ УНИВЕРСАЛЬНЫЙ КПУ-2Н",
    image: "13.WEBP",
    alias: "form_13",
    parent: 0,
  },
  {
    id: 14,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "ДРАЙКУЛЛЕРЫ МАВО.Д",
    image: "14.WEBP",
    alias: "form_14",
    parent: 0,
  },
  {
    id: 15,
    title: "Опросный лист на проектирование и изготовление оборудования:",
    subtitle: "ВОЗДУШНЫЕ КОНДЕНСАТОРЫ МАВО.К",
    image: "15.WEBP",
    alias: "form_15",
    parent: 0,
  },
];

export {
  catalogData,
  sertificatesData as certificatesData,
  questionnairesData,
};
